---
- name: attach parallels tools cd
  command: prlctl installtools {{ inventory_hostname }}
  delegate_to: 127.0.0.1
  vars:
    ansible_become: no

- name: mount cd in guest
  command: mount /dev/cdrom /mnt
  args:
    warn: false

- name: install parallels tools
  command: /mnt/install --install-unattended-with-deps

- name: unmount cd in guest
  command: umount /mnt

- name: eject cd
  command: eject
