---
- name: check for 32-bit support
  command: dpkg --print-foreign-architectures
  register: archs

- name: enable 32-bit as a multiarch
  command: dpkg --add-architecture i386
  register: added

- name: update apt
  apt:
    update_cache: yes
  when: added.changed

- name: install dev packages
  apt:
    name: "{{ pkgs }}"
    update_cache: no
    state: present
  vars:
    pkgs:
      - gcc-multilib
