#!/usr/bin/env ansible-playbook
---
- hosts: all
  tasks:
  - name: load variables
    include_vars:
      dir: vars
      ignore_files: [example.yml]

  - name: Set timezone to GMT
    timezone:
      name: GMT

  - name: Configure hostname
    include_role:
      name: hostname

  - name: Set up the regular user account
    include_role:
      name: user-setup
    vars:
      ansible_become: no

  - name: Set up the root account
    include_role:
      name: user-setup

  - name: Add proxy scripts
    include_role:
      name: proxy-setup
    when: proxy_servers is defined

  - name: Configure ssh daemon
    include_role:
      name: sshd-settings

  - name: Refresh inventory because ssh password -> key may have changed
    meta: refresh_inventory

  - name: Configure sudo
    include_role:
      name: sudo-nopasswd

  - name: Install powershell
    include_role:
      name: powershell

  - name: Install visual studio code
    include_role:
      name: vscode

  - name: Update apt
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Remove common packages
    apt:
      name: "{{ remove_pkgs }}"
      state: absent
      purge: yes
    vars:
      remove_pkgs:
        - popularity-contest

  - name: Upgrade system packages
    apt:
      update_cache: no
      upgrade: yes

  - name: Install base system packages
    apt:
      name: "{{ pkgs }}"
      update_cache: no
      state: present
    vars:
      pkgs:
        - curl
        - debconf-utils
        - dnsutils
        - dos2unix
        - ftp
        - git
        - jq
        - mtr
        - ncftp
        - openvpn
        - python3
        - python3-pip
        - rsync
        - smbclient
        - socat
        - tcpdump
        - tmux
        - traceroute
        - unrar-free
        - unzip
        - vim
        - wget
        - wireshark

  - name: Install extra packages from customizations
    apt:
      name: "{{ extra_pkgs }}"
      update_cache: no
      state: present

  - name: call apt autoremove
    apt:
      autoremove: yes

  - include_role:
      name: tools-setup
