---
- name: install veil package dependencies
  apt:
    name: "{{ pkgs }}"
    update_cache: no
    state: present
  vars:
    pkgs:
      - unzip
      - git
      - metasploit-framework
      - mingw-w64
      - mono-mcs
      - ruby
      - python3
      - python3-crypto
      - wine
      - wine32
      - wine64

- name: pull veil repo from github
  git:
    repo: 'https://github.com/Veil-Framework/Veil.git'
    dest: /opt/veil
