---
- name: install pentest system packages
  apt:
    name: "{{ pkgs }}"
    update_cache: yes
    state: present
  vars:
    pkgs:
      - burpsuite
      - exploitdb
      - gobuster
      - hashcat
      - hydra
      - john
      - libimage-exiftool-perl
      - metasploit-framework
      - netcat
      - nikto
      - nmap
      - python-scapy
      - python3-scapy
      - recon-ng
      - seclists
      - sqlmap
      - veil
      - wfuzz
      - zaproxy

- name: start postgres for metasploit
  service:
    name: postgresql
    enabled: yes
    state: started

- name: init db for metasploit
  command: msfdb init
  register: msfdb
  changed_when: '"skipping initialization" not in msfdb.stdout'

# - name: pull payloadsallthethings repo from github
#   git:
#     repo: 'https://github.com/swisskyrepo/PayloadsAllTheThings.git'
#     dest: /opt/payloadsallthethings

# - name: pull linenum repo from github
#   git:
#     repo: 'https://github.com/rebootuser/LinEnum.git'
#     dest: /opt/linenum

# - name: pull big-list-of-naughty-strings repo from github
#   git:
#     repo: 'https://github.com/minimaxir/big-list-of-naughty-strings.git'
#     dest: /opt/big-list-of-naughty-strings
