---
- name: download ghidra zip
  get_url:
    url: "{{ ghidra_url }}"
    checksum: "sha256:{{ ghidra_sha256 }}"
    dest: /root/ghidra.zip

- name: extract ghidra zip
  unarchive:
    src: /root/ghidra.zip
    dest: /opt
    remote_src: yes
    keep_newer: yes
