---
- name: set authorized key for remote user, copying it from current user
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"

- name: set bash profile
  copy:
    src: profile
    dest: "~/.profile"
    backup: yes

- name: set bashrc
  copy:
    src: bashrc
    dest: "~/.bashrc"
    backup: yes

- name: set vimrc
  copy:
    src: vimrc
    dest: "~/.vimrc"
    backup: yes

- name: add manual proxy var file
  copy:
    src: proxy-vars
    dest: "~/proxy-vars"
    backup: yes
