set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
"set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()

" let Vundle manage Vundle, required
" Plugin 'gmarik/Vundle.vim'
"Plugin 'git@github.com:gmarik/vundle.git'

" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin
"Plugin 'git@github.com:vim-scripts/indentpython.vim'
"Plugin 'git@github.com:scrooloose/syntastic'
"Plugin 'git@github.com:nvie/vim-flake8'
"Plugin 'git@github.com:Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
"call vundle#end()            " required

filetype plugin indent on

set encoding=utf-8
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent

let python_highlight_all=1
syntax on
