---
- name: Install requirements
  apt:
    name: "{{ pkgs }}"
    update_cache: no
    state: present
  vars:
    pkgs:
      - golang
      - git

- name: Install gobuster from github
  command: go get github.com/OJ/gobuster

- name: Link gobuster binary to opt
  file:
    src: /root/go/bin/gobuster
    dest: /opt/gobuster
    state: link
