---
- name: Import GPG keys from rvm.io
  shell: "curl -sSL https://rvm.io/{{ item }} | gpg --batch --import -"
  with_items:
    - mpapis.asc
    - pkuczynski.asc

- name: Install ruby through rvm
  include_role:
    name: rvm.ruby
  vars:
    rvm1_rubies: ['ruby-2.6.2']
    rvm1_install_flags: '--auto-dotfiles'
    rvm1_install_path: /usr/local/rvm
    rvm1_user: root
    rvm1_gpg_keys: ''
